# Site settings
name: Atom
email: ojs0106@gmail.com
author: atom
url: https://atomwoww.github.io/
github: https://github.com/atomwoww/
baseurl: ""

description: Atom의 Tech Blog
motto: 낙서하는 개발자
# banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: atomwoww

# Build settings
markdown: kramdown

