# Site settings
name: Atom의 Tech Blog
email: ojs0106@gmail.com
author: atom
url: https://atomthink.com
resume_site: https://atomthink.com/about
baseurl: ""
description: Atom의 Tech Blog
motto: 낙서하는 개발자

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: atomwoww
# Tracker
analytics: UA-146505718-1
# Build settings
markdown: kramdown

gems:
  - jekyll-paginate

exclude:
  - README.md
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor  